---
apiVersion: v1
clusters:
  -
    cluster:
      certificate-authority-data: DATA+OMITTED
      server: "https://127.0.0.1:16443"
    name: microk8s-cluster
contexts:
  -
    context:
      cluster: microk8s-cluster
      namespace: dev
      user: admin
    name: develop
  -
    context:
      cluster: microk8s-cluster
      user: admin
    name: microk8s
  -
    context:
      cluster: microk8s-cluster
      namespace: prod
      user: admin
    name: production
  -
    context:
      cluster: microk8s-cluster
      namespace: stag
      user: admin
    name: staging
current-context: develop
kind: Config
preferences: {}
users:
  -
    name: admin
    user:
      token: <PLACEHOLDER>
