---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-deployment
  labels:
    app: {{.Release.Name}}
spec:
  replicas: {{.Values.core.replicaCount}}
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      name: {{.Release.Name}}-pod
      labels:
        app: {{.Release.Name}}
    spec:
      securityContext:
        fsGroup: 123
      containers:
        - name: {{.Release.Name}}-container
          image: {{.Values.core.container.image}}:{{.Values.core.container.tag}}
          ports:
            - containerPort: {{.Values.core.container.port}}
          readinessProbe:
            httpGet:
              path: {{.Values.core.container.healthEndpoint}}
              port: {{.Values.core.container.port}}
            initialDelaySeconds: 5
            timeoutSeconds: 40
          livenessProbe:
            httpGet:
              path: {{.Values.core.container.healthEndpoint}}
              port: {{.Values.core.container.port}}
            initialDelaySeconds: 10
            timeoutSeconds: 40
          volumeMounts:
            - name: {{.Release.Name}}-volume
              mountPath: {{.Values.core.container.volumeMountPath}}
      volumes:
        - name: {{.Release.Name}}-volume
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-pvc
