---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
spec:
  rules:
    - host: {{.Values.core.ingress.dnsName}}
      http:
        paths:
          - backend:
              service:
                name: {{.Release.Name}}-svc
                port:
                  number: {{.Values.core.container.port}}
            path: {{.Values.core.container.healthEndpoint}}
            pathType: Prefix
