---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  labels:
    app: {{.Release.Name}}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{.Values.core.container.port}}
      targetPort: {{.Values.core.container.port}}
  selector:
    app: {{.Release.Name}}
