---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc
  labels:
    app: {{.Release.Name}}
spec:
  type: {{.Values.service.type}}
  ports:
    - protocol: {{.Values.service.protocol}}
      port: {{.Values.container.containerPort}}
      targetPort: {{.Values.container.containerPort}}
  selector:
    app: {{.Release.Name}}
