---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        -
          matchExpressions:
            -
              key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
