apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/core-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
