---
core:
  replicaCount: 1

  container:
    image: jmatejka/happy-bank-core
    tag: 0.2.1
    port: 5000
    volumeMountPath: /data
    healthEndpoint: /health

  persistentVol:
    accessMode: ReadWriteOnce
    capacity: 1Gi
    localPath: /data
    node: minikube
    reclaimPolicy: Retain
    storageClass: local-storage

  persistentVolClaim:
    accessMode: ReadWriteOnce
    capacity: 1Gi
    storageClass: local-storage

  ingress:
    dnsName: core.happybank.io

  secret:
    type: Opaque
    token: PENPUkVfVE9LRU4+

  redis:
    host: 127.0.0.1
    port: 6379

  verification:
    completions: 1
    backoffLimit: 2
    containerName: curl-container
    image: appropriate/curl
    restartPolicy: OnFailure
